
export type DocumentationTag =
  | "Frontend"
  | "Backend"
  | "Fullstack"
  | "Framework"
  | "Library"
  | "DevOps"
  | "Database"
  | "Testing"
  | "Security"
  | "Performance"
  | "Tools"
  | "Architecture"
  | "Best Practices"
  | "UI/UX"
  | "API"
  | "Cloud"
  | "AI/ML"
  | "Mobile"
  | "Game Development"
  | "IoT"
  | "Networking"
  | "DevTools"
  | "Containerization"
  | "Data Science"
  | "Big Data"
  | "Blockchain"
  | "Quantum Computing"
  | "Embedded Systems"
  | "Robotics"
  | "AR/VR"
  | "Accessibility"
  | "CMS"
  | "SEO"
  | "CI/CD"
  | "NoCode/LowCode"
  | "Design Patterns"
  | "Serverless"
  | "PWA"
  | "Microservices"
  | "ORM";
